<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sales;
use Doctrine\ORM\EntityRepository;

/**
 * SalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRepository extends EntityRepository
{
	/**
	 * @return Sales
	 */
	public function createNew()
	{
		return new Sales();
	}
	
	/**
	 * @param Sales $sale
	 */
	public function save(Sales $sale)
	{
		$this->_em->persist($sale);
		$this->_em->flush();
	}
}
